version: '3'
services:
  lisk-node:
    restart: always
    image: {IMAGE_NAME}:latest
    ports:
      - "{PORT}:{PORT}"
    environment:
      - DATABASE_HOST=postgresql
      - DATABASE_NAME=lisk_{CONTEXT}
      - DATABASE_USER=lisk
      - DATABASE_PASSWORD=password
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB={0|1|2}
      - FORGING_WHITELIST_IP=172.0.0.1
      - LOG_LEVEL=info
    links:
      - PostgreSQL:postgresql
      - Redis:redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
  PostgreSQL:
    restart: always
    image: postgres:9.6.5
    environment:
      - POSTGRES_USER=lisk
      - POSTGRES_PASSWORD=password
    volumes:
      - /etc/localtime:/etc/localtime:ro
  Redis:
    restart: always
    image: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
